#include "A.h"




void A::+perimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-600b698a:16deea5401e:-8000:0000000000000C11 begin
{
}
// section -64--88-19-1-600b698a:16deea5401e:-8000:0000000000000C11 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void A::+size()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-600b698a:16deea5401e:-8000:0000000000000C13 begin
{
}
// section -64--88-19-1-600b698a:16deea5401e:-8000:0000000000000C13 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
