#include "Adhérant.h"




void Adhérant::Emprunter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:0000000000000872 begin
{
}
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:0000000000000872 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adhérant::Rendre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:0000000000000874 begin
{
}
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:0000000000000874 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
