#include "Bibliothèque.h"




void Bibliothèque::AjouterDoc()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:0000000000000879 begin
{
}
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:0000000000000879 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bibliothèque::AjouterAdh()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:0000000000000881 begin
{
}
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:0000000000000881 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bibliothèque::SupprimerAdh()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:00000000000008A1 begin
{
}
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:00000000000008A1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
