#include "Emprunt.h"




void Emprunt::ProlongerDateRetour()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:00000000000008AA begin
{
}
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:00000000000008AA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
