#include "Livre.h"




void Livre::empruntable()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:00000000000008B5 begin
{
}
// section -64--88-19-1-4c435f79:16e1cec7b93:-8000:00000000000008B5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
